import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ResumeProvider } from "@/contexts/ResumeContext";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={cn(
                    inter.className,
                    "w-full h-full bg-black text-white"
                )}
            >
                <ResumeProvider>
                    {children}
                    <Toaster />
                </ResumeProvider>
            </body>
        </html>
    );
}
